name: Build Docker images

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        biome-version: ["1.9.2"]
        os: [alpine, debian]
        # alpine-version: ["3.20", "3.19"]
        # debian-version: ["bookworm", "bullseye"]
        include:
          - os: alpine
            alpine-version: "3.20"
            suffix: alpine3.20
          - os: alpine
            alpine-version: "3.19"
            suffix: alpine3.19
          - os: debian
            debian-version: "bookworm"
            suffix: bookworm
          - os: debian
            debian-version: "bullseye"
            suffix: bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/nhedger/biome
          flavor: |
            latest=auto
            suffix=-${{ matrix.os }}-${{ matrix.suffix }}
          tags: |
            type=sha
            type=semver,pattern={{major}},value=${{ matrix.biome-version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.biome-version }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.biome-version }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }} 
          file: ${{ matrix.os }}.Dockerfile
          build-args: |
            BIOME_VERSION=${{ matrix.biome-version }}
            ALPINE_VERSION=${{ matrix.alpine-version }}
            DEBIAN_VERSION=${{ matrix.debian-version }}