name: Build Docker images

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        biome-version: [1.9.2]
        include:
          - alpine-version: 3.20
            dockerfile: alpine.Dockerfile
            tag-suffix: alpine3.20
          - alpine-version: 3.19
            dockerfile: alpine.Dockerfile
            tag-suffix: alpine3.19
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/nhedger/biome
          flavor: |
            latest=auto
            suffix=-${{ matrix.tag-suffix }}
          tags: |
            type=sha
            type=raw,value=${{ matrix.biome-version }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }} 
          file: ${{ matrix.dockerfile }}
          build-args: |
            BIOME_VERSION=${{ matrix.biome-version }}
            ALPINE_VERSION=${{ matrix.alpine-version }}