name: Build Docker images

on:
  push:
    branches:
      - main

jobs:
  build-images:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        biome-version: ["1.9.2", "1.9.1", "1.9.0", "1.8.3", "1.8.2", "1.8.1", "1.8.0"]
        os:
          - name: alpine
            version: "3.20"
            suffix: "alpine3.20"
          - name: alpine
            version: "3.19"
            suffix: "alpine3.19"
          - name: debian
            version: "bookworm"
            suffix: "bookworm"
          - name: debian
            version: "bullseye"
            suffix: "bullseye"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/nhedger/biome
          flavor: |
            latest=auto
            suffix=-${{ matrix.os.suffix }}
          tags: |
            type=sha
            type=semver,pattern={{major}},value=${{ matrix.biome-version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.biome-version }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.biome-version }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: push
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }} 
          file: ${{ matrix.os.name }}.Dockerfile
          build-args: |
            BIOME_VERSION=${{ matrix.biome-version }}
            ALPINE_VERSION=${{ matrix.os.version }}
            DEBIAN_VERSION=${{ matrix.os.version }}